# -*- coding: utf-8 -*-
"""KBS3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVzzhmzHgttpWnd6zWVcZWW20lj0BY6C
"""

!pip install numpy scikit-learn skrebate

import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import LeaveOneOut
from skrebate import ReliefF

data = load_breast_cancer()
X, y = data.data, data.target

X = StandardScaler().fit_transform(X)
n_features = X.shape[1]

relief = ReliefF(n_neighbors=10, n_features_to_select=n_features)
relief.fit(X, y)

scores = relief.feature_importances_

selected_idx = np.where(scores > 0)[0]
X_reduced = X[:, selected_idx]

print(f"Original features: {n_features}")
print(f"After ReliefF: {X_reduced.shape[1]}")

def random_chromosome(n):
    return np.random.randint(0, 2, size=n)

def fitness(chromosome, X, y, alpha=0.01):
    if chromosome.sum() == 0:
        return 0.0

    X_sel = X[:, chromosome == 1]
    loo = LeaveOneOut()
    clf = KNeighborsClassifier(n_neighbors=1)

    correct = 0
    for train, test in loo.split(X_sel):
        clf.fit(X_sel[train], y[train])
        correct += clf.predict(X_sel[test])[0] == y[test][0]

    accuracy = correct / len(y)
    penalty = alpha * (chromosome.sum() / X.shape[1])

    return accuracy - penalty

def local_search(chromosome, X, y):
    best = chromosome.copy()
    best_score = fitness(best, X, y)

    d = len(chromosome) // 10
    idxs = np.random.choice(len(chromosome), d, replace=False)

    for idx in idxs:
        if best[idx] == 0:
            candidate = best.copy()
            candidate[idx] = 1

            score = fitness(candidate, X, y)
            if score > best_score:
                best, best_score = candidate, score

    return best

def crossover(p1, p2):
    point = np.random.randint(1, len(p1)-1)
    return np.concatenate([p1[:point], p2[point:]])

def mutate(chromosome, rate=0.1):
    for i in range(len(chromosome)):
        if np.random.rand() < rate:
            chromosome[i] = 1 - chromosome[i]
    return chromosome

def memetic_algorithm(X, y, pop_size=30, generations=50):
    n = X.shape[1]
    population = [random_chromosome(n) for _ in range(pop_size)]

    # Initial local search
    for i in range(pop_size):
        population[i] = local_search(population[i], X, y)

    for gen in range(generations):
        idx1, idx2 = np.random.choice(len(population), 2, replace=False)
        p1 = population[idx1]
        p2 = population[idx2]
        if np.random.rand() < 0.5:
            child = crossover(p1, p2)
        else:
            child = mutate(p1.copy())

        child = local_search(child, X, y)


        scores = [fitness(c, X, y) for c in population]
        best_idx = np.argmax(scores)
        worst_idx = np.argmin(scores)

        if fitness(child, X, y) > scores[worst_idx]:
            population[worst_idx] = child
            scores[worst_idx] = fitness(child, X, y)

        best_idx = np.argmax(scores)
        print(
            f"Gen {gen}: "
            f"best fitness = {scores[best_idx]:.4f}, "
            f"features = {population[best_idx].sum()}"
        )

    scores = [fitness(c, X, y) for c in population]
    best = population[np.argmax(scores)]
    return best

best_solution = memetic_algorithm(X_reduced, y)

final_accuracy = fitness(best_solution, X_reduced, y)
selected_features = best_solution.sum()

print("Final accuracy:", final_accuracy)
print("Selected features:", selected_features)